
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: ePac
* Environment: Production
* Id: 4cadf737-f623-0004-1317-e48e55f12839
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames =
  | "de-AT"
  | "de-DE"
  | "default"
  | "en-AU"
  | "en-CA"
  | "en-GB"
  | "en-GH"
  | "es-ES"
  | "fr"
  | "id"
  | "pl";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "article"
  | "blog_post"
  | "call_to_action"
  | "customer_spotlight"
  | "disclaimer"
  | "event"
  | "landing_page"
  | "page"
  | "person"
  | "product"
  | "service"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames =
  | "academic_content"
  | "default"
  | "marketing_resources"
  | "operations"
  | "patient_resources";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames =
  | "academic_resources"
  | "biographies"
  | "default"
  | "patient_resources"
  | "product_workflow";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "article_type"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "medical_specialties";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "archived"
  | "copy_review"
  | "draft_8405a5b"
  | "draft_97d445e"
  | "draft_a8b162c"
  | "draft_b242d4d"
  | "draft"
  | "legal_review"
  | "marketing_review_9f2362c"
  | "marketing_review"
  | "peer_review"
  | "product_review"
  | "published"
  | "reviewed_1778942"
  | "reviewed"
  | "scheduled"
  | "staff_member_review"
  | "translation";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "article_type"
  | "author"
  | "autoplay"
  | "background_image"
  | "biography"
  | "body_copy"
  | "body"
  | "brand_image"
  | "button_label"
  | "button_link"
  | "caption"
  | "cta_link"
  | "cta_text"
  | "description"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "first_name"
  | "guidelines"
  | "headline"
  | "hero_button_text"
  | "hero_button_url"
  | "hero_content"
  | "hero_image"
  | "hero_text"
  | "image_position"
  | "image"
  | "introduction"
  | "job_title"
  | "last_name"
  | "medical_specialties"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "name"
  | "phone"
  | "prefix"
  | "product_image"
  | "publish_date"
  | "referral_text"
  | "related_articles"
  | "start_date"
  | "subheadline"
  | "subpages"
  | "suffixes"
  | "summary"
  | "team"
  | "title"
  | "topics"
  | "type"
  | "url_slug"
  | "url"
  | "video_link"
  | "website";
