
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: ePac
* Environment: Production
* Id: 4cadf737-f623-0004-1317-e48e55f12839
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Customer Spotlight
 *
 * Id: 6a598c57-da89-4a1c-be27-eae03280f0b4
 * Codename: customer_spotlight
 */
export type CustomerSpotlight = CoreContentType<
  CustomerSpotlightElementCodenames,
  {
    /**
     * Background Image
     *
     * Type: asset
     * Required: false
     * Codename: background_image
     * Id: d3660cc7-face-459a-aa33-aae0ef3d1a55
     */
    readonly background_image: Elements.AssetsElement;
    /**
     * Product Image
     *
     * Type: asset
     * Required: false
     * Codename: product_image
     * Id: eef6897a-6067-4c3e-b81a-854c15b88f94
     */
    readonly product_image: Elements.AssetsElement;
    /**
     * Brand Image
     *
     * Type: asset
     * Required: false
     * Codename: brand_image
     * Id: 175ed8db-f21b-44e9-8f30-cf5b4d6acc4c
     * Guidelines: This is the brand that we are spotlighting
     */
    readonly brand_image: Elements.AssetsElement;
    /**
     * Referral Text
     *
     * Type: text
     * Required: false
     * Codename: referral_text
     * Id: 8486950a-61dc-44e5-93f1-318548cecfd5
     */
    readonly referral_text: Elements.TextElement;
  },
  "customer_spotlight"
>;

/**
 * Type representing all available element codenames for Customer Spotlight
 */
export type CustomerSpotlightElementCodenames = "background_image" | "product_image" | "brand_image" | "referral_text";

/**
 * Type guard for Customer Spotlight
 *
 * Id: 6a598c57-da89-4a1c-be27-eae03280f0b4
 * Codename: customer_spotlight
 */
export function isCustomerSpotlight(item: CoreContentType | undefined | null): item is CustomerSpotlight {
  return item?.system?.type === "customer_spotlight";
}
