
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: ePac
* Environment: Production
* Id: 4cadf737-f623-0004-1317-e48e55f12839
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Product
 *
 * Id: 3ed5b8ee-8894-42c7-bf1f-76438fde47a0
 * Codename: product
 */
export type Product = CoreContentType<
  ProductElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: false
     * Codename: name
     * Id: f3285f92-0643-4002-8ea8-85d559661a28
     */
    readonly name: Elements.TextElement;
    /**
     * Hero Text
     *
     * Type: rich_text
     * Required: false
     * Codename: hero_text
     * Id: 0c8abce3-0543-4849-8312-9e18d1e901b9
     */
    readonly hero_text: Elements.RichTextElement<CoreContentType>;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: false
     * Codename: hero_image
     * Id: 293b635f-30ab-45fd-9dcd-ff782f4b2651
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * CTA Link
     *
     * Type: text
     * Required: false
     * Codename: cta_link
     * Id: ed1e2137-4d97-4c9e-89b3-6653384edae3
     */
    readonly cta_link: Elements.TextElement;
    /**
     * CTA Text
     *
     * Type: text
     * Required: false
     * Codename: cta_text
     * Id: ec5b5179-7551-4f26-acc8-ab01960dc24b
     * Guidelines: Request a Quote
     */
    readonly cta_text: Elements.TextElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: 8bdf4ed6-c4f8-47ab-a847-29f96027f0d4
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
  },
  "product"
>;

/**
 * Type representing all available element codenames for Product
 */
export type ProductElementCodenames = "name" | "hero_text" | "hero_image" | "cta_link" | "cta_text" | "body";

/**
 * Type guard for Product
 *
 * Id: 3ed5b8ee-8894-42c7-bf1f-76438fde47a0
 * Codename: product
 */
export function isProduct(item: CoreContentType | undefined | null): item is Product {
  return item?.system?.type === "product";
}
