
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: ePac
* Environment: Production
* Id: 4cadf737-f623-0004-1317-e48e55f12839
* 
* -------------------------------------------------------------------------------
**/

export * from "./metadata.ts";
